manifest:
  remotes:
    - name: zmkfirmware-infused-kim
      url-base: https://github.com/infused-kim
    - name: zephyr-dododo
      url-base: https://github.com/bobobo1618
  projects:
    - name: zmk
      remote: zephyr-dododo #zmkfirmware-infused-kim
      revision: fix-oled #my-changes/oled-ext-pwr
      import: app/west.yml
  self:
    path: config
